### PR TITLE
Added BSD3-Clause license.

### PR DESCRIPTION
**Pull request by Rembane**
This makes the project open source.

https://spdx.org/licenses/BSD-3-Clause-Clear.html#licenseText

### CODE REVIEW

**Comment by Rembane** [comment]
#5 is the issue that led to this pull request.

**Comment by mbark** [comment]
Could you also add the appropriate LICENSE file to the repository root?

**Comment by Rembane** [comment]
Yes! I forgot to run `git add`, sorry!

**Comment by Rembane** [comment]
I just added a LICENSE-file. Check it out! :D

**Comment by mbark** [comment]
Merged! Thanks! :)

**Pull request merged**
